// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0zJ7bOo10swnRMu_ioVefVDqNztXPl50',
    appId: '1:726112946640:web:718f698e40ee90c70dd1d5',
    messagingSenderId: '726112946640',
    projectId: 'app-visa-card',
    authDomain: 'app-visa-card.firebaseapp.com',
    storageBucket: 'app-visa-card.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGJ3oV65840vfWS8MD8q8qyMPDm7aHkRo',
    appId: '1:726112946640:android:2375247dc7e854270dd1d5',
    messagingSenderId: '726112946640',
    projectId: 'app-visa-card',
    storageBucket: 'app-visa-card.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqr5No5lr0cMvtxxb6oI85RWcFmmpkl84',
    appId: '1:726112946640:ios:6ac730d52e3c27fd0dd1d5',
    messagingSenderId: '726112946640',
    projectId: 'app-visa-card',
    storageBucket: 'app-visa-card.firebasestorage.app',
    iosBundleId: 'com.example.appMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqr5No5lr0cMvtxxb6oI85RWcFmmpkl84',
    appId: '1:726112946640:ios:6ac730d52e3c27fd0dd1d5',
    messagingSenderId: '726112946640',
    projectId: 'app-visa-card',
    storageBucket: 'app-visa-card.firebasestorage.app',
    iosBundleId: 'com.example.appMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0zJ7bOo10swnRMu_ioVefVDqNztXPl50',
    appId: '1:726112946640:web:37f9e753cfc073600dd1d5',
    messagingSenderId: '726112946640',
    projectId: 'app-visa-card',
    authDomain: 'app-visa-card.firebaseapp.com',
    storageBucket: 'app-visa-card.firebasestorage.app',
  );
}
